import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import CartAccessProvider from "@/components/layout/CartAccessProvider";
import { AuthProvider } from "@/providers/AuthProvider";
import { Toaster } from "sonner"; // Import the Toaster component from sonner

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Header />
        <AuthProvider>
          <CartAccessProvider>
            <main className="min-h-screen">{children}</main>
            {/* Add the Sonner Toaster component here */}
            <Toaster position="top-right" richColors closeButton />
          </CartAccessProvider>
        </AuthProvider>
        <Footer />
      </body>
    </html>
  );
}